//! Graphic Events
//!
//! Events generated by the graphic engine and sent to the worker thread for dispatch to mods.

use super::WidgetType;
use serde::Serialize;

/// Events generated by the graphic engine
///
/// These events are sent from the engine thread (main) to the worker thread
/// via `tokio::sync::mpsc` channel, then dispatched to mods through the event system.
#[derive(Debug, Clone)]
pub enum GraphicEvent {
    // ========== Window Events ==========
    /// Window was successfully created
    WindowCreated {
        /// The window ID
        window_id: u64,
    },

    /// Window was closed
    WindowClosed {
        /// The window ID
        window_id: u64,
    },

    /// Window was resized
    WindowResized {
        /// The window ID
        window_id: u64,
        /// New width in pixels
        width: u32,
        /// New height in pixels
        height: u32,
    },

    /// Window focus changed
    WindowFocused {
        /// The window ID
        window_id: u64,
        /// Whether the window gained focus
        focused: bool,
    },

    /// Window was moved
    WindowMoved {
        /// The window ID
        window_id: u64,
        /// New X position
        x: i32,
        /// New Y position
        y: i32,
    },

    // ========== Keyboard Events ==========
    /// Key was pressed
    KeyPressed {
        /// The window ID where the event occurred
        window_id: u64,
        /// Key identifier (e.g., "KeyA", "Space", "Escape")
        key: String,
        /// Active modifiers
        modifiers: KeyModifiers,
    },

    /// Key was released
    KeyReleased {
        /// The window ID where the event occurred
        window_id: u64,
        /// Key identifier
        key: String,
        /// Active modifiers
        modifiers: KeyModifiers,
    },

    /// Character input (for text input)
    CharacterInput {
        /// The window ID where the event occurred
        window_id: u64,
        /// The character that was input
        character: char,
    },

    // ========== Mouse Events ==========
    /// Mouse was moved
    MouseMoved {
        /// The window ID where the event occurred
        window_id: u64,
        /// X position in window coordinates
        x: f32,
        /// Y position in window coordinates
        y: f32,
    },

    /// Mouse button was pressed
    MouseButtonPressed {
        /// The window ID where the event occurred
        window_id: u64,
        /// Which button was pressed
        button: MouseButton,
        /// X position
        x: f32,
        /// Y position
        y: f32,
    },

    /// Mouse button was released
    MouseButtonReleased {
        /// The window ID where the event occurred
        window_id: u64,
        /// Which button was released
        button: MouseButton,
        /// X position
        x: f32,
        /// Y position
        y: f32,
    },

    /// Mouse wheel was scrolled
    MouseWheel {
        /// The window ID where the event occurred
        window_id: u64,
        /// Horizontal scroll delta
        delta_x: f32,
        /// Vertical scroll delta
        delta_y: f32,
    },

    // ========== Frame Events ==========
    /// Frame is starting (called at beginning of each frame)
    FrameStart {
        /// The window ID (0 for primary/all)
        window_id: u64,
        /// Time since last frame in seconds
        delta_time: f32,
    },

    /// Frame has ended
    FrameEnd {
        /// The window ID
        window_id: u64,
        /// Total frame time in seconds
        frame_time: f32,
    },

    // ========== Engine Lifecycle ==========
    /// Engine is ready to receive commands
    EngineReady,

    /// Engine encountered an error
    EngineError {
        /// Error description
        message: String,
    },

    /// Engine is shutting down
    EngineShuttingDown,

    // ========== Widget Events ==========
    /// Widget was successfully created
    WidgetCreated {
        /// Parent window ID
        window_id: u64,
        /// The widget ID
        widget_id: u64,
        /// Widget type
        widget_type: WidgetType,
    },

    /// Widget was destroyed
    WidgetDestroyed {
        /// Parent window ID
        window_id: u64,
        /// The widget ID
        widget_id: u64,
    },

    /// Widget was clicked
    WidgetClicked {
        /// Parent window ID
        window_id: u64,
        /// The widget ID
        widget_id: u64,
        /// Click X position within widget
        x: f32,
        /// Click Y position within widget
        y: f32,
        /// Mouse button that was clicked
        button: MouseButton,
    },

    /// Widget hover state changed
    WidgetHovered {
        /// Parent window ID
        window_id: u64,
        /// The widget ID
        widget_id: u64,
        /// True if mouse entered, false if left
        entered: bool,
        /// Mouse X position within widget
        x: f32,
        /// Mouse Y position within widget
        y: f32,
    },

    /// Widget focus state changed
    WidgetFocused {
        /// Parent window ID
        window_id: u64,
        /// The widget ID
        widget_id: u64,
        /// True if gained focus, false if lost
        focused: bool,
    },

    /// Widget interaction state changed (for internal tracking)
    WidgetInteractionChanged {
        /// Parent window ID
        window_id: u64,
        /// The widget ID
        widget_id: u64,
        /// New interaction state: "none", "hovered", "pressed"
        interaction: String,
    },
}

impl GraphicEvent {
    /// Get the event name for dispatch to mods
    pub fn event_name(&self) -> &'static str {
        match self {
            Self::WindowCreated { .. } => "graphic:window:created",
            Self::WindowClosed { .. } => "graphic:window:closed",
            Self::WindowResized { .. } => "graphic:window:resized",
            Self::WindowFocused { .. } => "graphic:window:focused",
            Self::WindowMoved { .. } => "graphic:window:moved",
            Self::KeyPressed { .. } => "graphic:input:keyPressed",
            Self::KeyReleased { .. } => "graphic:input:keyReleased",
            Self::CharacterInput { .. } => "graphic:input:character",
            Self::MouseMoved { .. } => "graphic:input:mouseMoved",
            Self::MouseButtonPressed { .. } => "graphic:input:mousePressed",
            Self::MouseButtonReleased { .. } => "graphic:input:mouseReleased",
            Self::MouseWheel { .. } => "graphic:input:mouseWheel",
            Self::FrameStart { .. } => "graphic:frame:start",
            Self::FrameEnd { .. } => "graphic:frame:end",
            Self::EngineReady => "graphic:engine:ready",
            Self::EngineError { .. } => "graphic:engine:error",
            Self::EngineShuttingDown => "graphic:engine:shuttingDown",
            // Widget events
            Self::WidgetCreated { .. } => "graphic:widget:created",
            Self::WidgetDestroyed { .. } => "graphic:widget:destroyed",
            Self::WidgetClicked { .. } => "graphic:widget:clicked",
            Self::WidgetHovered { .. } => "graphic:widget:hovered",
            Self::WidgetFocused { .. } => "graphic:widget:focused",
            Self::WidgetInteractionChanged { .. } => "graphic:widget:interactionChanged",
        }
    }

    /// Convert event data to JSON args for dispatch
    pub fn to_json_args(&self) -> Vec<String> {
        match self {
            Self::WindowCreated { window_id } => {
                vec![window_id.to_string()]
            }
            Self::WindowClosed { window_id } => {
                vec![window_id.to_string()]
            }
            Self::WindowResized {
                window_id,
                width,
                height,
            } => {
                vec![
                    window_id.to_string(),
                    width.to_string(),
                    height.to_string(),
                ]
            }
            Self::WindowFocused { window_id, focused } => {
                vec![window_id.to_string(), focused.to_string()]
            }
            Self::WindowMoved { window_id, x, y } => {
                vec![window_id.to_string(), x.to_string(), y.to_string()]
            }
            Self::KeyPressed {
                window_id,
                key,
                modifiers,
            } => {
                vec![
                    window_id.to_string(),
                    format!("\"{}\"", key),
                    serde_json::to_string(modifiers).unwrap_or_else(|_| "{}".to_string()),
                ]
            }
            Self::KeyReleased {
                window_id,
                key,
                modifiers,
            } => {
                vec![
                    window_id.to_string(),
                    format!("\"{}\"", key),
                    serde_json::to_string(modifiers).unwrap_or_else(|_| "{}".to_string()),
                ]
            }
            Self::CharacterInput {
                window_id,
                character,
            } => {
                vec![window_id.to_string(), format!("\"{}\"", character)]
            }
            Self::MouseMoved { window_id, x, y } => {
                vec![window_id.to_string(), x.to_string(), y.to_string()]
            }
            Self::MouseButtonPressed {
                window_id,
                button,
                x,
                y,
            } => {
                vec![
                    window_id.to_string(),
                    format!("\"{}\"", button.as_str()),
                    x.to_string(),
                    y.to_string(),
                ]
            }
            Self::MouseButtonReleased {
                window_id,
                button,
                x,
                y,
            } => {
                vec![
                    window_id.to_string(),
                    format!("\"{}\"", button.as_str()),
                    x.to_string(),
                    y.to_string(),
                ]
            }
            Self::MouseWheel {
                window_id,
                delta_x,
                delta_y,
            } => {
                vec![
                    window_id.to_string(),
                    delta_x.to_string(),
                    delta_y.to_string(),
                ]
            }
            Self::FrameStart {
                window_id,
                delta_time,
            } => {
                vec![window_id.to_string(), delta_time.to_string()]
            }
            Self::FrameEnd {
                window_id,
                frame_time,
            } => {
                vec![window_id.to_string(), frame_time.to_string()]
            }
            Self::EngineReady => vec![],
            Self::EngineError { message } => {
                vec![format!("\"{}\"", message.replace('"', "\\\""))]
            }
            Self::EngineShuttingDown => vec![],
            // Widget events
            Self::WidgetCreated {
                window_id,
                widget_id,
                widget_type,
            } => {
                vec![
                    window_id.to_string(),
                    widget_id.to_string(),
                    format!("\"{}\"", widget_type),
                ]
            }
            Self::WidgetDestroyed {
                window_id,
                widget_id,
            } => {
                vec![window_id.to_string(), widget_id.to_string()]
            }
            Self::WidgetClicked {
                window_id,
                widget_id,
                x,
                y,
                button,
            } => {
                vec![
                    window_id.to_string(),
                    widget_id.to_string(),
                    x.to_string(),
                    y.to_string(),
                    format!("\"{}\"", button.as_str()),
                ]
            }
            Self::WidgetHovered {
                window_id,
                widget_id,
                entered,
                x,
                y,
            } => {
                vec![
                    window_id.to_string(),
                    widget_id.to_string(),
                    entered.to_string(),
                    x.to_string(),
                    y.to_string(),
                ]
            }
            Self::WidgetFocused {
                window_id,
                widget_id,
                focused,
            } => {
                vec![
                    window_id.to_string(),
                    widget_id.to_string(),
                    focused.to_string(),
                ]
            }
            Self::WidgetInteractionChanged {
                window_id,
                widget_id,
                interaction,
            } => {
                vec![
                    window_id.to_string(),
                    widget_id.to_string(),
                    format!("\"{}\"", interaction),
                ]
            }
        }
    }
}

/// Keyboard modifier keys state
#[derive(Debug, Clone, Default, Serialize)]
pub struct KeyModifiers {
    /// Shift key is pressed
    pub shift: bool,
    /// Ctrl key is pressed (Command on macOS)
    pub ctrl: bool,
    /// Alt key is pressed (Option on macOS)
    pub alt: bool,
    /// Meta key is pressed (Windows key / Command on macOS)
    pub meta: bool,
}

impl KeyModifiers {
    /// Create with no modifiers
    pub fn none() -> Self {
        Self::default()
    }

    /// Check if any modifier is pressed
    pub fn any(&self) -> bool {
        self.shift || self.ctrl || self.alt || self.meta
    }
}

/// Mouse button identifier
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseButton {
    /// Left mouse button
    Left,
    /// Right mouse button
    Right,
    /// Middle mouse button (wheel click)
    Middle,
    /// Other button (with index)
    Other(u8),
}

impl MouseButton {
    /// Get button as string for JavaScript
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Left => "left",
            Self::Right => "right",
            Self::Middle => "middle",
            Self::Other(_) => "other",
        }
    }

    /// Convert from u8
    pub fn from_u8(value: u8) -> Self {
        match value {
            0 => Self::Left,
            1 => Self::Right,
            2 => Self::Middle,
            n => Self::Other(n),
        }
    }
}
