//! Graphic Events
//!
//! Events generated by the graphic engine and sent to the main thread.

use super::input::FrameSnapshot;

/// Events generated by the graphic engine
#[derive(Clone, Debug)]
pub enum GraphicEvent {
    // === Window Events ===
    /// A new window was created
    WindowCreated { window_id: u64 },
    /// A window was closed
    WindowClosed { window_id: u64 },
    /// A window was resized
    WindowResized { window_id: u64, width: u32, height: u32 },
    /// A window gained or lost focus
    WindowFocused { window_id: u64, focused: bool },
    /// A window was moved
    WindowMoved { window_id: u64, x: i32, y: i32 },

    // === Keyboard Events ===
    /// A key was pressed
    KeyPressed { window_id: u64, key: String, modifiers: KeyModifiers },
    /// A key was released
    KeyReleased { window_id: u64, key: String, modifiers: KeyModifiers },
    /// A character was typed (for text input)
    CharacterInput { window_id: u64, character: char },

    // === Mouse Events ===
    /// Mouse cursor moved
    MouseMoved { window_id: u64, x: f32, y: f32 },
    /// Mouse button pressed
    MouseButtonPressed { window_id: u64, button: MouseButton, x: f32, y: f32 },
    /// Mouse button released
    MouseButtonReleased { window_id: u64, button: MouseButton, x: f32, y: f32 },
    /// Mouse wheel scrolled
    MouseWheel { window_id: u64, delta_x: f32, delta_y: f32 },

    // === Frame Events ===
    /// Frame is starting (includes input snapshot for this frame)
    FrameStart { snapshot: FrameSnapshot },
    /// Frame has ended
    FrameEnd { frame_time: f32 },

    // === Engine Lifecycle ===
    /// Engine is ready to receive commands
    EngineReady,
    /// Engine encountered an error
    EngineError { message: String },
    /// Engine is shutting down
    EngineShuttingDown,
}

/// Keyboard modifier keys state
#[derive(Clone, Debug, Default)]
pub struct KeyModifiers {
    /// Shift key is pressed
    pub shift: bool,
    /// Ctrl key is pressed
    pub ctrl: bool,
    /// Alt key is pressed
    pub alt: bool,
    /// Meta key is pressed (Cmd on macOS, Win on Windows)
    pub meta: bool,
}

/// Mouse button identifier
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum MouseButton {
    /// Left mouse button
    Left,
    /// Right mouse button
    Right,
    /// Middle mouse button (wheel click)
    Middle,
    /// Other button with numeric ID
    Other(u8),
}

impl MouseButton {
    /// Convert to string representation
    pub fn as_str(&self) -> &'static str {
        match self {
            MouseButton::Left => "left",
            MouseButton::Right => "right",
            MouseButton::Middle => "middle",
            MouseButton::Other(_) => "other",
        }
    }
}
